/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.intern.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MiniBlogEntry service. Represents a row in the &quot;DG_MiniBlogEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.intern.service.model.impl.MiniBlogEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.intern.service.model.impl.MiniBlogEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MiniBlogEntry
 * @generated
 */
@ProviderType
public interface MiniBlogEntryModel
	extends BaseModel<MiniBlogEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mini blog entry model instance should use the {@link MiniBlogEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this mini blog entry.
	 *
	 * @return the primary key of this mini blog entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mini blog entry.
	 *
	 * @param primaryKey the primary key of this mini blog entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this mini blog entry.
	 *
	 * @return the uuid of this mini blog entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this mini blog entry.
	 *
	 * @param uuid the uuid of this mini blog entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this mini blog entry.
	 *
	 * @return the ID of this mini blog entry
	 */
	public long getId();

	/**
	 * Sets the ID of this mini blog entry.
	 *
	 * @param id the ID of this mini blog entry
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this mini blog entry.
	 *
	 * @return the group ID of this mini blog entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this mini blog entry.
	 *
	 * @param groupId the group ID of this mini blog entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mini blog entry.
	 *
	 * @return the company ID of this mini blog entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mini blog entry.
	 *
	 * @param companyId the company ID of this mini blog entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mini blog entry.
	 *
	 * @return the user ID of this mini blog entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mini blog entry.
	 *
	 * @param userId the user ID of this mini blog entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mini blog entry.
	 *
	 * @return the user uuid of this mini blog entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mini blog entry.
	 *
	 * @param userUuid the user uuid of this mini blog entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mini blog entry.
	 *
	 * @return the user name of this mini blog entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mini blog entry.
	 *
	 * @param userName the user name of this mini blog entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mini blog entry.
	 *
	 * @return the create date of this mini blog entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mini blog entry.
	 *
	 * @param createDate the create date of this mini blog entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mini blog entry.
	 *
	 * @return the modified date of this mini blog entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mini blog entry.
	 *
	 * @param modifiedDate the modified date of this mini blog entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this mini blog entry.
	 *
	 * @return the title of this mini blog entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this mini blog entry.
	 *
	 * @param title the title of this mini blog entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the image of this mini blog entry.
	 *
	 * @return the image of this mini blog entry
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this mini blog entry.
	 *
	 * @param image the image of this mini blog entry
	 */
	public void setImage(String image);

	/**
	 * Returns the short description of this mini blog entry.
	 *
	 * @return the short description of this mini blog entry
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this mini blog entry.
	 *
	 * @param shortDescription the short description of this mini blog entry
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the long description of this mini blog entry.
	 *
	 * @return the long description of this mini blog entry
	 */
	@AutoEscape
	public String getLongDescription();

	/**
	 * Sets the long description of this mini blog entry.
	 *
	 * @param longDescription the long description of this mini blog entry
	 */
	public void setLongDescription(String longDescription);

	@Override
	public MiniBlogEntry cloneWithOriginalValues();

}