/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.intern.service.service.base;

import com.dogoo.intern.service.model.MiniBlogEntry;
import com.dogoo.intern.service.service.MiniBlogEntryLocalService;
import com.dogoo.intern.service.service.MiniBlogEntryLocalServiceUtil;
import com.dogoo.intern.service.service.persistence.DGContactEntryPersistence;
import com.dogoo.intern.service.service.persistence.MiniBlogEntryPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the mini blog entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dogoo.intern.service.service.impl.MiniBlogEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dogoo.intern.service.service.impl.MiniBlogEntryLocalServiceImpl
 * @generated
 */
public abstract class MiniBlogEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, MiniBlogEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MiniBlogEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>MiniBlogEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the mini blog entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiniBlogEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param miniBlogEntry the mini blog entry
	 * @return the mini blog entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MiniBlogEntry addMiniBlogEntry(MiniBlogEntry miniBlogEntry) {
		miniBlogEntry.setNew(true);

		return miniBlogEntryPersistence.update(miniBlogEntry);
	}

	/**
	 * Creates a new mini blog entry with the primary key. Does not add the mini blog entry to the database.
	 *
	 * @param id the primary key for the new mini blog entry
	 * @return the new mini blog entry
	 */
	@Override
	@Transactional(enabled = false)
	public MiniBlogEntry createMiniBlogEntry(long id) {
		return miniBlogEntryPersistence.create(id);
	}

	/**
	 * Deletes the mini blog entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiniBlogEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the mini blog entry
	 * @return the mini blog entry that was removed
	 * @throws PortalException if a mini blog entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MiniBlogEntry deleteMiniBlogEntry(long id) throws PortalException {
		return miniBlogEntryPersistence.remove(id);
	}

	/**
	 * Deletes the mini blog entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiniBlogEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param miniBlogEntry the mini blog entry
	 * @return the mini blog entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MiniBlogEntry deleteMiniBlogEntry(MiniBlogEntry miniBlogEntry) {
		return miniBlogEntryPersistence.remove(miniBlogEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return miniBlogEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			MiniBlogEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return miniBlogEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.intern.service.model.impl.MiniBlogEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return miniBlogEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.intern.service.model.impl.MiniBlogEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return miniBlogEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return miniBlogEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return miniBlogEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public MiniBlogEntry fetchMiniBlogEntry(long id) {
		return miniBlogEntryPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the mini blog entry matching the UUID and group.
	 *
	 * @param uuid the mini blog entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching mini blog entry, or <code>null</code> if a matching mini blog entry could not be found
	 */
	@Override
	public MiniBlogEntry fetchMiniBlogEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return miniBlogEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the mini blog entry with the primary key.
	 *
	 * @param id the primary key of the mini blog entry
	 * @return the mini blog entry
	 * @throws PortalException if a mini blog entry with the primary key could not be found
	 */
	@Override
	public MiniBlogEntry getMiniBlogEntry(long id) throws PortalException {
		return miniBlogEntryPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(miniBlogEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MiniBlogEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			miniBlogEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MiniBlogEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(miniBlogEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MiniBlogEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<MiniBlogEntry>() {

				@Override
				public void performAction(MiniBlogEntry miniBlogEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, miniBlogEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(MiniBlogEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return miniBlogEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return miniBlogEntryLocalService.deleteMiniBlogEntry(
			(MiniBlogEntry)persistedModel);
	}

	@Override
	public BasePersistence<MiniBlogEntry> getBasePersistence() {
		return miniBlogEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return miniBlogEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the mini blog entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the mini blog entries
	 * @param companyId the primary key of the company
	 * @return the matching mini blog entries, or an empty list if no matches were found
	 */
	@Override
	public List<MiniBlogEntry> getMiniBlogEntriesByUuidAndCompanyId(
		String uuid, long companyId) {

		return miniBlogEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of mini blog entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the mini blog entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of mini blog entries
	 * @param end the upper bound of the range of mini blog entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching mini blog entries, or an empty list if no matches were found
	 */
	@Override
	public List<MiniBlogEntry> getMiniBlogEntriesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<MiniBlogEntry> orderByComparator) {

		return miniBlogEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the mini blog entry matching the UUID and group.
	 *
	 * @param uuid the mini blog entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching mini blog entry
	 * @throws PortalException if a matching mini blog entry could not be found
	 */
	@Override
	public MiniBlogEntry getMiniBlogEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return miniBlogEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the mini blog entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.intern.service.model.impl.MiniBlogEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of mini blog entries
	 * @param end the upper bound of the range of mini blog entries (not inclusive)
	 * @return the range of mini blog entries
	 */
	@Override
	public List<MiniBlogEntry> getMiniBlogEntries(int start, int end) {
		return miniBlogEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of mini blog entries.
	 *
	 * @return the number of mini blog entries
	 */
	@Override
	public int getMiniBlogEntriesCount() {
		return miniBlogEntryPersistence.countAll();
	}

	/**
	 * Updates the mini blog entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MiniBlogEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param miniBlogEntry the mini blog entry
	 * @return the mini blog entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MiniBlogEntry updateMiniBlogEntry(MiniBlogEntry miniBlogEntry) {
		return miniBlogEntryPersistence.update(miniBlogEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MiniBlogEntryLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		miniBlogEntryLocalService = (MiniBlogEntryLocalService)aopProxy;

		_setLocalServiceUtilService(miniBlogEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MiniBlogEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MiniBlogEntry.class;
	}

	protected String getModelClassName() {
		return MiniBlogEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = miniBlogEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		MiniBlogEntryLocalService miniBlogEntryLocalService) {

		try {
			Field field = MiniBlogEntryLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, miniBlogEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected DGContactEntryPersistence dgContactEntryPersistence;

	protected MiniBlogEntryLocalService miniBlogEntryLocalService;

	@Reference
	protected MiniBlogEntryPersistence miniBlogEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}